"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var asyncHandler_1 = require("../../handler/asyncHandler");
var PetTypeController_1 = require("../../controllers/PetTypeController");
var validator_1 = require("../../middleware/validator");
var pet_type_1 = require("../../schema/pet_type");
var router = (0, express_1.Router)();
// router.use(authentication);
router.post("/create", (0, validator_1.default)(pet_type_1.default.petTypeCreate), (0, asyncHandler_1.default)(PetTypeController_1.default.create));
router.put("/update", (0, validator_1.default)(pet_type_1.default.petTypeUpdate), (0, asyncHandler_1.default)(PetTypeController_1.default.update));
router.delete("/delete/:id", (0, asyncHandler_1.default)(PetTypeController_1.default.delete));
exports.default = router;
