"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var asyncHandler_1 = require("../../handler/asyncHandler");
var CartItemController_1 = require("../../controllers/CartItemController");
var validator_1 = require("../../middleware/validator");
var cart_item_1 = require("../../schema/cart_item");
var router = (0, express_1.Router)();
// router.use(authentication);
router.post("/create", (0, validator_1.default)(cart_item_1.default.cartItemCreate), (0, asyncHandler_1.default)(CartItemController_1.default.create));
router.put("/update", (0, validator_1.default)(cart_item_1.default.cartItemUpdate), (0, asyncHandler_1.default)(CartItemController_1.default.update));
router.delete("/delete/:id", (0, asyncHandler_1.default)(CartItemController_1.default.delete));
exports.default = router;
