"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var pet_1 = require("./pet");
var pet_type_1 = require("./pet_type");
var accessory_1 = require("./accessory");
var accessory_type_1 = require("./accessory_type");
var promotion_1 = require("./promotion");
var product_promotion_1 = require("./product_promotion");
var product_feedback_1 = require("./product_feedback");
var cart_1 = require("./cart");
var cart_item_1 = require("./cart_item");
var order_1 = require("./order");
var order_detail_1 = require("./order_detail");
var auth_1 = require("./auth");
var user_1 = require("./user");
var router = (0, express_1.Router)();
router.use("/pet", pet_1.default);
router.use("/pet-type", pet_type_1.default);
router.use("/accessory", accessory_1.default);
router.use("/accessory-type", accessory_type_1.default);
router.use("/auth", auth_1.default);
router.use("/user", user_1.default);
router.use("/promotion", promotion_1.default);
router.use("/product-promotion", product_promotion_1.default);
router.use("/product-feedback", product_feedback_1.default);
router.use("/cart", cart_1.default);
router.use("/cart-item", cart_item_1.default);
router.use("/order", order_1.default);
router.use("/order-detail", order_detail_1.default);
exports.default = router;
