"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var asyncHandler_1 = require("../../handler/asyncHandler");
var PetController_1 = require("../../controllers/PetController");
var validator_1 = require("../../middleware/validator");
var pet_1 = require("../../schema/pet");
var router = (0, express_1.Router)();
// router.use(authentication);
router.post("/create", (0, validator_1.default)(pet_1.default.petCreate), (0, asyncHandler_1.default)(PetController_1.default.create));
router.put("/update", (0, validator_1.default)(pet_1.default.petUpdate), (0, asyncHandler_1.default)(PetController_1.default.update));
router.delete("/delete/:id", (0, asyncHandler_1.default)(PetController_1.default.delete));
exports.default = router;
