"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var asyncHandler_1 = require("../../handler/asyncHandler");
var AccessoryController_1 = require("../../controllers/AccessoryController");
var validator_1 = require("../../middleware/validator");
var accessory_1 = require("../../schema/accessory");
var router = (0, express_1.Router)();
// router.use(authentication);
router.post("/create", (0, validator_1.default)(accessory_1.default.accessoryCreate), (0, asyncHandler_1.default)(AccessoryController_1.default.create));
router.put("/update", (0, validator_1.default)(accessory_1.default.accessoryUpdate), (0, asyncHandler_1.default)(AccessoryController_1.default.update));
router.delete("/delete/:id", (0, asyncHandler_1.default)(AccessoryController_1.default.delete));
exports.default = router;
