"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var asyncHandler_1 = require("../../handler/asyncHandler");
var OrderController_1 = require("../../controllers/OrderController");
var validator_1 = require("../../middleware/validator");
var order_1 = require("../../schema/order");
var router = (0, express_1.Router)();
// router.use(authentication);
router.post("/create", (0, validator_1.default)(order_1.default.orderCreate), (0, asyncHandler_1.default)(OrderController_1.default.create));
router.put("/update", (0, validator_1.default)(order_1.default.orderUpdate), (0, asyncHandler_1.default)(OrderController_1.default.update));
router.delete("/delete/:id", (0, asyncHandler_1.default)(OrderController_1.default.delete));
exports.default = router;
